### PR TITLE
Add an example .travis.yml to README.md

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by mislav** [comment]
Thanks! I'm going to try this in my Travis build. I presume you then save build artefacts somewhere as prebuilt binaries for a specific release, for example?

**Comment by tianon** [comment]
You certainly could accomplish that!

How to do so is out of scope for gimme IMO though -- that's more of a
general Travis thing (saving artifacts externally).

**Comment by mislav** [comment]
@tianon Naturally. It would be done either by Travis' [build artifacts feature](http://docs.travis-ci.com/user/uploading-artifacts/) or I would do it manually with [my S3 uploader script](https://github.com/github/hub/blob/97eb02bda48a0f50f5d9c153b031c4e3e5042069/script/s3-put).

The third option would be using a GitHub OAuth token to push binaries directly to GitHub Releases.

**Comment by tianon** [comment]
:+1: :metal:

**Comment by mislav** [comment]
I have [had success using Gimme to cross-compile on Travis](https://github.com/travis-ci/travis-ci/issues/2207#issuecomment-109572217). However, I didn't see the point of setting up a Travis build matrix. The primary point of the build matrix is to make it easy to see on overview which environments failed the build. Since there's nothing to fail during cross-compilation, because tests can't be run for produced builds, it makes more sense to perform the cross-compilation in a single job.

**Comment by tianon** [comment]
I personally do a build matrix so that they can build concurrently because
I want a green check on my PRs as quickly as possible. :smile:

**Comment by mislav** [comment]
The concurrency benefit is a good point. So do you have Go tests for your projects running for at least one of these environments, say "linux amd64", while all other jobs in the matrix get green by default just as soon as they finish compiling the binary?

**Comment by tianon** [comment]
@mislav I usually do something like this for running tests: (which is basically what you describe)

``` bash
- if [ "$(go env GOOS)/$(go env GOARCH)" = "$(go env GOHOSTOS)/$(go env GOHOSTARCH)" ]; then
    go test ./...;
  fi
```

**Pull request merged**
