### PR TITLE
Add explicit arm64 support and try to download the new official "arm6" binary tarballs

### PR DESCRIPTION
**Pull request by tianon**
Ref #27

### CODE REVIEW

**Comment by tianon** [comment]
This one's untested ATM -- need to find some ARMv6+ hardware to give it a shot.

**Comment by pierrre** [comment]
The reply thread in interesting https://twitter.com/davecheney/status/677662689682964481

**Comment by tianon** [comment]
Indeed! :smile:

**Comment by tianon** [comment]
Finally tested this in an `armhf` environment (since the published binaries link against `/lib/ld-linux-armhf.so.3` explicitly):

``` console
root@ce171fa8e80a:/# wget -c 'https://raw.githubusercontent.com/travis-ci/gimme/improved-arm-support/gimme'
--2015-12-30 19:05:58--  https://raw.githubusercontent.com/travis-ci/gimme/improved-arm-support/gimme
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.44.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.44.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12735 (12K) [text/plain]
Saving to: 'gimme'

gimme               100%[===================>]  12.44K  --.-KB/s    in 0s      

2015-12-30 19:05:58 (66.7 MB/s) - 'gimme' saved [12735/12735]

root@ce171fa8e80a:/# chmod +x gimme 
root@ce171fa8e80a:/# mv gimme /usr/local/bin/
root@ce171fa8e80a:/# GIMME_ARCH=arm gimme 1.6beta1

unset GOOS
unset GOARCH
export GOROOT="/root/.gimme/versions/go1.6beta1.linux.arm"
export PATH="/root/.gimme/versions/go1.6beta1.linux.arm/bin:${PATH}"
go version >&2

export GIMME_ENV="/root/.gimme/envs/go1.6beta1.env"
root@ce171fa8e80a:/# unset GOOS
root@ce171fa8e80a:/# unset GOARCH
root@ce171fa8e80a:/# export GOROOT="/root/.gimme/versions/go1.6beta1.linux.arm"
root@ce171fa8e80a:/# export PATH="/root/.gimme/versions/go1.6beta1.linux.arm/bin:${PATH}"
root@ce171fa8e80a:/# go version >&2
go version go1.6beta1 linux/arm
```

:+1:

**Comment by broady** [comment]
FYI, we'll be releasing using `armv6l` for the final 1.6 release (1.6 beta 2 uses this scheme)

**Comment by tianon** [comment]
Oh, thanks for the heads up! :+1:

**Pull request merged**
