### PR TITLE
Add go1.7rc3 ~ go1.7rc5 + 1.7rc6

### PR DESCRIPTION
**Pull request by zchee**
I was added multiple versions. It's ok?

### CODE REVIEW

**Comment by ekaley** [comment]
add rc6 now

**Comment by zchee** [comment]
@ekaley Done :)

**Comment by nathany** [comment]
Go 1.7 is out :-)

**Comment by zchee** [comment]
@nathany lol
okay, will do!!

**Comment by Songmu** [comment]
How about it? @zchee

**Comment by zchee** [comment]
@Songmu Ah! sorry, forgot :(
done.

# 

However, travis go language environment will work 1.7 without this pull request.
Why? It really needs?

**Comment by Songmu** [comment]
@zchee  Oh sorry, It's my misconception.

I don't realize this is only testdata issue and `gimme` already(automatically) supported go1.7...

**Comment by zchee** [comment]
@Songmu Yeah, I tested go1.7rc5 on
https://github.com/zchee/docker-machine-driver-xhyve/blob/master/.travis.yml
but travis passes the test.
https://travis-ci.org/zchee/docker-machine-driver-xhyve/jobs/150755834.

Where is maintainer~~ \o/

**Comment by nathany** [comment]
see https://github.com/travis-ci/gimme/pull/41#issuecomment-209200999

**Comment by tianon** [comment]
LGTM, thanks!

**Pull request merged**
