### PR TITLE
Add 1.6beta1 as a "known binary version"

### LINKED ISSUE #27: Use Go 1.6 as bootstrap
Go 1.6beta1 is out, can you add Go 1.6 as a bootstrap candidate?
By the way, shouldn't you test candidates in reverse order? (1.6, 1.5 and 1.4).
It makes more sense to use the most recent version of Go.

Also, the ARM architecture is now officially available in downloads (https://golang.org/dl/#go1.6beta1)
But they only provide the ARM6 binary: https://storage.googleapis.com/golang/go1.6beta1.linux-arm6.tar.gz
In the URL: it's "arm6" and not "arm".
But https://storage.googleapis.com/golang/go1.6beta1.linux-arm.tar.gz also works...

### PR DESCRIPTION
**Pull request by tianon**
Fixes #27

### CODE REVIEW

**Comment by tianon** [comment]
@pierrre this will add 1.6 support -- I've got some ARM improvements I'll make as a separate PR too; thanks! :heart:

**Comment by pierrre** [comment]
Thank **you** :)

What is the usage of `.known-source-versions-xxx`?
It's not updated?

**Comment by tianon** [comment]
Those files are really just used for Travis -- https://github.com/travis-ci/gimme/blob/master/.travis.yml :smile: (ie, a nice long list of explicit versions we can test to make sure we're still working properly)

**Comment by curtisallen** [comment]
anyway we can get this merged?

**Comment by tianon** [comment]
Yeah sorry!  Was just waiting for Travis and then lost track of it.

**Comment by curtisallen** [comment]
Thanks!

**Pull request merged**
