### PR TITLE
Install -race directory after compile

### LINKED ISSUE #77: should use `./all.bash` instead of `./make.bash` for installation from source?
Please see https://github.com/golang/go/issues/18486.

`./make.bash` doesn't install "$GOROOT/pkg/$GOOS_$GOARCH_race" directory.
Therefore some tests could be failed. 
Somehow we need to install it manually or use `./all.bash` instead. I guess.

Thanks.

### PR DESCRIPTION
**Pull request by hirochachacha**
Fixes #77

### CODE REVIEW

**Comment by meatballhat** [comment]
@hirochachacha I don't think I'm comfortable with this being the default behavior.  Could you modify so that it's available via an env var such as `GIMME_INSTALL_RACE`?  Also, could you modify so that the `go` tool is invoked via an absolute path?

If you feel strongly about this being the default behavior, please push back 😄

**Comment by tianon** [comment]
@meatballhat I don't have opinions regarding doing this by default, but regarding the absolute path to `go` -- we don't actually have that available here; this happens in a subshell where we've done `cd "${1}"` followed by `cd src`, so `../bin/go` will be the correct `go` in this particular instance

**Comment by hirochachacha** [comment]
I will create a new PR and address those suggestions, thanks.

**Comment by hirochachacha** [comment]
https://github.com/travis-ci/gimme/pull/82 is new one.

**Pull request closed without merging**
