### PR TITLE
Support go 1.5 rc1

### PR DESCRIPTION
**Pull request by dlsniper**

### CODE REVIEW

**Comment by dlsniper** [comment]
I'll send a PR for go1.5 when it is live

**Comment by tianon** [comment]
LGTM :+1:

cc @meatballhat

**Comment by tianon** [comment]
Heh, forgot I actually have merge here.

Thanks! :tada:

**Comment by tianon** [comment]
Should this be added in `.known-binary-versions-darwin` too?

**Comment by dlsniper** [comment]
@tianon yes, I think so. I'm just using this on linux so I've totally ignored darwin, I'll send another PR soon.

**Comment by tianon** [comment]
Rockin', thanks! :metal:

**Pull request merged**
