### PR TITLE
Add alias `stable`

### PR DESCRIPTION
**Pull request by thatguystone**
From the discussion of #39

### CODE REVIEW

**Comment by kodawah** [comment]
:+1: 
I hope it gets merged soon!

**Comment by kodawah** [comment]
@BanzaiMan @tianon @fsouza ping review I guess?

**Comment by meatballhat** [comment]
I'm very much on the fence about this one.  @tianon thoughts?

**Comment by meatballhat** [comment]
@kodabb Can you take a peek at the conflicts? :heart:

**Pull request merged**
